<?php
/**
 * Copyright (c) 2013-2015 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2015 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/** @var EbayEnterprise_Coupons_Block_Checkout_Cart_Coupon $this */
?>
<div class="discount">

    <h2><?php echo $this->__('Discount Codes') ?></h2>

    <form id="discount-coupon-form" action="<?php echo $this->getUrl('coupons/cart/post') ?>" method="post">

        <div class="discount-form">

            <label for="coupon_code">
                <?php echo $this->__('Enter your coupon code if you have any.') ?>
            </label>

            <input type="hidden" name="remove" id="remove-coupone" value="0" />

            <div class="input-box">
                <input class="input-text" id="coupon_code" name="coupon_code" value="" />
            </div>

            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
            </div>

        </div>

    </form>


    <?php if ($this->getAppliedCoupons()): ?>

        <h2><?php echo $this->__('Applied Coupons'); ?></h2>

        <table border="0" width="100%" cellpadding="4" cellspacing="0" style="padding-top: 3px;">

            <?php foreach ($this->getAppliedCoupons() as $index => $coupon): ?>

                <tr style="padding-bottom: 3px;">

                    <td><?php echo $coupon; ?></td>

                    <td style="text-align: right;">

                        <form id="discount-coupon-cancel-form-<?php echo $index; ?>" action="<?php echo $this->getUrl('coupons/cart/cancel') ?>" method="post">

                            <input type="hidden" name="coupon_code_cancel" value="<?php echo $coupon; ?>" />

                            <a href="#" onclick="javascript: discountForm.cancel('<?php echo $index; ?>'); return false;"><?php echo $this->__('Cancel'); ?></a>

                        </form>

                    </td>

                </tr>

            <?php endforeach; ?>

        </table>

    <?php endif; ?>

</div>

<script type="text/javascript">
    //<![CDATA[
    var discountForm = new VarienForm('discount-coupon-form');
    discountForm.submit = function (isRemove) {
        if (isRemove) {
            $('coupon_code').removeClassName('required-entry');
            $('remove-coupone').value = "1";
        } else {
            $('coupon_code').addClassName('required-entry');
            $('remove-coupone').value = "0";
        }
        return VarienForm.prototype.submit.bind(discountForm)();
    };
    
    discountForm.cancel = function(index){
        $('discount-coupon-cancel-form-' + index).submit();
    };
    //]]>
</script>
